# Form implementation generated from reading ui file 'FicheEntree.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Ficheentree(object):
    def setupUi(self, Ficheentree):
        Ficheentree.setObjectName("Ficheentree")
        Ficheentree.resize(1482, 866)
        Ficheentree.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(parent=Ficheentree)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(550, 730, 425, 31))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.reglement = QtWidgets.QCheckBox(parent=self.formLayoutWidget_2)
        self.reglement.setObjectName("reglement")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.reglement)
        self.formLayoutWidget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(650, 760, 221, 61))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.connecter = QtWidgets.QPushButton(parent=self.formLayoutWidget_3)
        self.connecter.setObjectName("connecter")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.connecter)
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 100, 261, 401))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.form_gauche = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.form_gauche.setContentsMargins(0, 0, 0, 0)
        self.form_gauche.setObjectName("form_gauche")
        self.formLayoutWidget_5 = QtWidgets.QWidget(parent=self.centralwidget)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(290, 100, 291, 401))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.form_centre = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.form_centre.setContentsMargins(0, 0, 0, 0)
        self.form_centre.setObjectName("form_centre")
        self.label_informations = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_informations.setGeometry(QtCore.QRect(200, 30, 281, 51))
        self.label_informations.setObjectName("label_informations")
        self.formLayoutWidget_7 = QtWidgets.QWidget(parent=self.centralwidget)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(750, 100, 721, 611))
        self.formLayoutWidget_7.setObjectName("formLayoutWidget_7")
        self.form_reglement = QtWidgets.QFormLayout(self.formLayoutWidget_7)
        self.form_reglement.setContentsMargins(0, 0, 0, 0)
        self.form_reglement.setObjectName("form_reglement")
        self.label_reglement = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_reglement.setGeometry(QtCore.QRect(910, 40, 521, 41))
        self.label_reglement.setObjectName("label_reglement")
        Ficheentree.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Ficheentree)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1482, 22))
        self.menubar.setObjectName("menubar")
        Ficheentree.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Ficheentree)
        self.statusbar.setObjectName("statusbar")
        Ficheentree.setStatusBar(self.statusbar)

        self.retranslateUi(Ficheentree)
        QtCore.QMetaObject.connectSlotsByName(Ficheentree)

    def retranslateUi(self, Ficheentree):
        _translate = QtCore.QCoreApplication.translate
        Ficheentree.setWindowTitle(_translate("Ficheentree", "MainWindow"))
        self.reglement.setText(_translate("Ficheentree", "J\'ai lu j\'accepte les conditions du règlement intérieur de l\'espace numérique"))
        self.connecter.setText(_translate("Ficheentree", "Ouvrir la session"))
        self.label_informations.setText(_translate("Ficheentree", "Vos informations"))
        self.label_reglement.setText(_translate("Ficheentree", "Règlement intérieur de l\'espace numérique"))
